apiVersion: v1
kind: Service
metadata:
  name: devops-df-svc-vol-2
  labels:
    name: df-svc-vol-2
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 12145
  selector:
    app: df-pod-vol-2