trigger:
  branches:
    include:
    - main
    - devops-azure
  paths:
    include:
    - devops/cicd/arm-bicep/*

variables:
  - group: 'df-cicd'

# ARM Deployment Stages

stages:  

  - stage: Lakehouse_Storage_Account
    jobs: 
      - job: DeployStorageAccount
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: '$(SERVICE_CONNECTION)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group create --resource-group $(RESOURCE_GROUP) --template-file devops/cicd/arm-bicep/storage_accounts.bicep --parameters '@devops/cicd/arm-bicep/storage_accounts_parameters.json' environment=$(ENVIRONMENT) project=$(PROJECT) storageAccountName=$(LAKEHOUSE_STORAGE_ACCOUNT) bronzeLayer=$(LAKEHOUSE_BRONZE_LAYER) silverLayer=$(LAKEHOUSE_SILVER_LAYER) goldLayer=$(LAKEHOUSE_GOLD_LAYER) location='$(REGION)'
           
  # - stage: Azure_SQL_Database
  #   jobs: 
  #     - job: DeployAzureSQL
  #       pool:
  #         vmImage: ubuntu-latest
  #       steps:
  #       - task: AzureCLI@2
  #         inputs:
  #           azureSubscription: '$(SERVICE_CONNECTION)'
  #           scriptType: 'bash'
  #           scriptLocation: 'inlineScript'
  #           inlineScript: |
  #             az --version
  #             az deployment group create --resource-group $(RESOURCE_GROUP) --template-file devops/cicd/arm-bicep/azure_sql.bicep --parameters '@devops/cicd/arm-bicep/azure_sql_parameters.json'
           