trigger:
  branches:
    include:
    - main
    - devops-azure
  paths:
    include:
    - devops/cicd/arm-bicep/*

variables:
  - group: 'df-cicd'

# ARM Deployment Stages

stages:  

  - stage: Lakehouse_Storage_Account
    jobs: 
      - job: DeployStorageAccount
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'df-cicd-service-connection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az --version
              az deployment group create --resource-group $(RESOURCE_GROUP) --template-file devops/cicd/arm-bicep/storage_accounts.json --parameters '@devops/cicd/arm-bicep/storage_accounts_parameters.json'
           